{
  "openapi": "3.1.0",
  "info": {
    "title": "agent-group-assignments",
    "version": "6.7.0",
    "description": "This document outlines the API contracts for HPE Networking UXI."
  },
  "servers": [
    {
      "url": "https://{host}",
      "variables": {
        "host": {
          "default": "api.capenetworks.com"
        }
      }
    }
  ],
  "security": [
    {
      "HTTPBearer": []
    }
  ],
  "tags": [
    {
      "name": "agent-group-assignments"
    }
  ],
  "paths": {
    "/networking-uxi/v1alpha1/agent-group-assignments": {
      "get": {
        "description": "Get a list of agent group assignments",
        "operationId": "agent_group_assignments_get",
        "parameters": [
          {
            "description": "The ID of the resource.",
            "in": "query",
            "name": "id",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "The ID of the resource.",
              "title": "ID"
            }
          },
          {
            "description": "The next cursor for pagination.",
            "in": "query",
            "name": "next",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "The next cursor for pagination.",
              "title": "Next"
            }
          },
          {
            "description": "The maximum number of items returned in the response.",
            "in": "query",
            "name": "limit",
            "required": false,
            "schema": {
              "default": 50,
              "description": "The maximum number of items returned in the response.",
              "maximum": 100,
              "minimum": 0,
              "title": "Limit",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "List of agent group assignments": {
                    "description": "List of agent group assignment retrieval.",
                    "summary": "List of agent group assignments",
                    "value": {
                      "count": 1,
                      "items": [
                        {
                          "agent": {
                            "id": "bff985d7-ef1d-4d49-84d6-5e3ed345dda1"
                          },
                          "group": {
                            "id": "4gergsdgdf4tr"
                          },
                          "id": "8419059c-1f4d-4cea-adf1-bd09654edba1",
                          "type": "networking-uxi/agent-group-assignment"
                        }
                      ],
                      "next": "aGVsbG8gZnJvbSBhbGlzdGFpcg=="
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/AgentGroupAssignmentsGetResponse"
                }
              }
            },
            "description": "Successful Response"
          },
          "400": {
            "content": {
              "application/json": {
                "examples": {
                  "Malformed cursor": {
                    "description": "The provided cursor could not be decoded.",
                    "summary": "Malformed cursor",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_NETWORKING_UXI_MALFORMED_CURSOR",
                      "httpStatusCode": 400,
                      "message": "The provided cursor could not be decoded."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_UNAUTHORIZED",
                      "httpStatusCode": 401,
                      "message": "You are not authorized to perform this action - the token is missing, expired, revoked, malformed, or invalid for other reasons"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Unauthorized"
          },
          "403": {
            "content": {
              "application/json": {
                "examples": {
                  "Forbidden": {
                    "description": "The user has insufficient permissions to complete the request.",
                    "summary": "Forbidden",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_FORBIDDEN",
                      "httpStatusCode": 403,
                      "message": "The user has insufficient permissions to complete the request."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Forbidden"
          },
          "405": {
            "content": {
              "application/json": {
                "examples": {
                  "Method Not Allowed": {
                    "description": "Method is not allowed.",
                    "summary": "Method Not Allowed",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_METHOD_NOT_ALLOWED",
                      "httpStatusCode": 405,
                      "message": "Method is not allowed."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Method Not Allowed"
          },
          "415": {
            "content": {
              "application/json": {
                "examples": {
                  "Unsupported Media Type": {
                    "description": "Media type is unsupported.",
                    "summary": "Unsupported Media Type",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_UNSUPPORTED_MEDIA_TYPE",
                      "httpStatusCode": 415,
                      "message": "Media type is unsupported."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Unsupported Media Type"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          },
          "429": {
            "content": {
              "application/json": {
                "examples": {
                  "Too Many Requests": {
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_TOO_MANY_REQUESTS",
                      "httpStatusCode": 429,
                      "message": "Too many requests."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Too Many Requests"
          },
          "500": {
            "content": {
              "application/json": {
                "examples": {
                  "Internal Server Error": {
                    "description": "The request cannot be processed due to an unknown issue.",
                    "summary": "Internal Server Error",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_INTERNAL_SERVER_ERROR",
                      "httpStatusCode": 500,
                      "message": "The request cannot be processed due to an unknown issue."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Internal Server Error"
          },
          "5XX": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Server Error"
          }
        },
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "summary": "Agent Group Assignments Get",
        "tags": [
          "agent-group-assignments"
        ],
        "x-stability-level": "alpha"
      },
      "post": {
        "description": "Create an agent group assignment",
        "operationId": "agent_group_assignment_post",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Create an agent group assignment": {
                  "description": "Create an agent group assignment",
                  "summary": "Create an agent group assignment",
                  "value": {
                    "agentId": "0f4c2917-9886-41bf-8ea6-faaea9fddbf0",
                    "groupId": "e0f97a387c31"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/AgentGroupAssignmentPostRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "Agent group assignment created": {
                    "description": "Agent group assignment successfully created.",
                    "summary": "Agent group assignment created",
                    "value": {
                      "agent": {
                        "id": "bff985d7-ef1d-4d49-84d6-5e3ed345dda1"
                      },
                      "group": {
                        "id": "4gergsdgdf4tr"
                      },
                      "id": "8419059c-1f4d-4cea-adf1-bd09654edba1",
                      "type": "networking-uxi/agent-group-assignment"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/AgentGroupAssignmentPostResponse"
                }
              }
            },
            "description": "Successful Response"
          },
          "400": {
            "content": {
              "application/json": {
                "examples": {
                  "Bad Request": {
                    "description": "The request could not be processed due to a validation error.",
                    "summary": "Bad Request",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_BAD_REQUEST",
                      "errorDetails": [
                        {
                          "issues": [
                            {
                              "description": "The request could not be processed due to a validation error.",
                              "source": "x-generic-header",
                              "subject": "header"
                            }
                          ],
                          "type": "hpe.greenlake.bad_request"
                        }
                      ],
                      "httpStatusCode": 400,
                      "message": "The request could not be processed due to a validation error."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_UNAUTHORIZED",
                      "httpStatusCode": 401,
                      "message": "You are not authorized to perform this action - the token is missing, expired, revoked, malformed, or invalid for other reasons"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Unauthorized"
          },
          "403": {
            "content": {
              "application/json": {
                "examples": {
                  "Forbidden": {
                    "description": "The user has insufficient permissions to complete the request.",
                    "summary": "Forbidden",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_FORBIDDEN",
                      "httpStatusCode": 403,
                      "message": "The user has insufficient permissions to complete the request."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Forbidden"
          },
          "405": {
            "content": {
              "application/json": {
                "examples": {
                  "Method Not Allowed": {
                    "description": "Method is not allowed.",
                    "summary": "Method Not Allowed",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_METHOD_NOT_ALLOWED",
                      "httpStatusCode": 405,
                      "message": "Method is not allowed."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Method Not Allowed"
          },
          "409": {
            "content": {
              "application/json": {
                "examples": {
                  "Assignment already exists": {
                    "description": "Resource already exists.",
                    "summary": "Assignment already exists",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_CONFLICT",
                      "httpStatusCode": 409,
                      "message": "Resource already exists."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Conflict"
          },
          "415": {
            "content": {
              "application/json": {
                "examples": {
                  "Unsupported Media Type": {
                    "description": "Media type is unsupported.",
                    "summary": "Unsupported Media Type",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_UNSUPPORTED_MEDIA_TYPE",
                      "httpStatusCode": 415,
                      "message": "Media type is unsupported."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Unsupported Media Type"
          },
          "422": {
            "content": {
              "application/json": {
                "examples": {
                  "Agent does not exist": {
                    "description": "Unable to assign agent to group - the specified agent does not exist.",
                    "summary": "Agent does not exist",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_NETWORKING_UXI_AGENT_DOES_NOT_EXIST",
                      "httpStatusCode": 422,
                      "message": "Unable to assign agent to group - the specified agent does not exist."
                    }
                  },
                  "Assignment to root group error": {
                    "description": "Unable to assign agent to group - the specified group is a root group.",
                    "summary": "Assignment to root group error",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_NETWORKING_UXI_CANNOT_ASSIGN_AGENT_TO_ROOT_GROUP",
                      "httpStatusCode": 422,
                      "message": "Unable to assign agent to group - the specified group is a root group."
                    }
                  },
                  "Group does not exist": {
                    "description": "Unable to assign agent to group - the specified group does not exist.",
                    "summary": "Group does not exist",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_NETWORKING_UXI_GROUP_DOES_NOT_EXIST",
                      "httpStatusCode": 422,
                      "message": "Unable to assign agent to group - the specified group does not exist."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Unprocessable Entity"
          },
          "429": {
            "content": {
              "application/json": {
                "examples": {
                  "Too Many Requests": {
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_TOO_MANY_REQUESTS",
                      "httpStatusCode": 429,
                      "message": "Too many requests."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Too Many Requests"
          },
          "500": {
            "content": {
              "application/json": {
                "examples": {
                  "Internal Server Error": {
                    "description": "The request cannot be processed due to an unknown issue.",
                    "summary": "Internal Server Error",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_INTERNAL_SERVER_ERROR",
                      "httpStatusCode": 500,
                      "message": "The request cannot be processed due to an unknown issue."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Internal Server Error"
          },
          "5XX": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Server Error"
          }
        },
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "summary": "Agent Group Assignment Post",
        "tags": [
          "agent-group-assignments"
        ],
        "x-stability-level": "alpha"
      }
    },
    "/networking-uxi/v1alpha1/agent-group-assignments/{id}": {
      "delete": {
        "description": "Delete the specified agent group assignment",
        "operationId": "agent_group_assignment_delete",
        "parameters": [
          {
            "description": "The unique identifier of the assignment",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "description": "The unique identifier of the assignment",
              "title": "Assignment ID",
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "400": {
            "content": {
              "application/json": {
                "examples": {
                  "Bad Request": {
                    "description": "The request could not be processed due to a validation error.",
                    "summary": "Bad Request",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_BAD_REQUEST",
                      "errorDetails": [
                        {
                          "issues": [
                            {
                              "description": "The request could not be processed due to a validation error.",
                              "source": "x-generic-header",
                              "subject": "header"
                            }
                          ],
                          "type": "hpe.greenlake.bad_request"
                        }
                      ],
                      "httpStatusCode": 400,
                      "message": "The request could not be processed due to a validation error."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Bad Request"
          },
          "401": {
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized": {
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_UNAUTHORIZED",
                      "httpStatusCode": 401,
                      "message": "You are not authorized to perform this action - the token is missing, expired, revoked, malformed, or invalid for other reasons"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Unauthorized"
          },
          "403": {
            "content": {
              "application/json": {
                "examples": {
                  "Forbidden": {
                    "description": "The user has insufficient permissions to complete the request.",
                    "summary": "Forbidden",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_FORBIDDEN",
                      "httpStatusCode": 403,
                      "message": "The user has insufficient permissions to complete the request."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Forbidden"
          },
          "404": {
            "content": {
              "application/json": {
                "examples": {
                  "Not Found": {
                    "description": "Resource not found.",
                    "summary": "Not Found",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_NOT_FOUND",
                      "httpStatusCode": 404,
                      "message": "Resource not found."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Not Found"
          },
          "405": {
            "content": {
              "application/json": {
                "examples": {
                  "Method Not Allowed": {
                    "description": "Method is not allowed.",
                    "summary": "Method Not Allowed",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_METHOD_NOT_ALLOWED",
                      "httpStatusCode": 405,
                      "message": "Method is not allowed."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Method Not Allowed"
          },
          "415": {
            "content": {
              "application/json": {
                "examples": {
                  "Unsupported Media Type": {
                    "description": "Media type is unsupported.",
                    "summary": "Unsupported Media Type",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_UNSUPPORTED_MEDIA_TYPE",
                      "httpStatusCode": 415,
                      "message": "Media type is unsupported."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Unsupported Media Type"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          },
          "429": {
            "content": {
              "application/json": {
                "examples": {
                  "Too Many Requests": {
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_TOO_MANY_REQUESTS",
                      "httpStatusCode": 429,
                      "message": "Too many requests."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Too Many Requests"
          },
          "500": {
            "content": {
              "application/json": {
                "examples": {
                  "Internal Server Error": {
                    "description": "The request cannot be processed due to an unknown issue.",
                    "summary": "Internal Server Error",
                    "value": {
                      "debugId": "1234567890",
                      "errorCode": "HPE_GL_ERROR_INTERNAL_SERVER_ERROR",
                      "httpStatusCode": 500,
                      "message": "The request cannot be processed due to an unknown issue."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Internal Server Error"
          },
          "5XX": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            },
            "description": "Server Error"
          }
        },
        "security": [
          {
            "HTTPBearer": []
          }
        ],
        "summary": "Agent Group Assignment Delete",
        "tags": [
          "agent-group-assignments"
        ],
        "x-stability-level": "alpha"
      }
    }
  },
  "components": {
    "schemas": {
      "AgentGroupAssignmentPostAgent": {
        "properties": {
          "id": {
            "description": "The unique identifier of the agent",
            "title": "Agent ID",
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "title": "AgentGroupAssignmentPostAgent",
        "type": "object"
      },
      "AgentGroupAssignmentPostGroup": {
        "properties": {
          "id": {
            "description": "The unique identifier of the group",
            "title": "Group ID",
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "title": "AgentGroupAssignmentPostGroup",
        "type": "object"
      },
      "AgentGroupAssignmentPostRequest": {
        "properties": {
          "agentId": {
            "description": "The unique identifier of the agent",
            "title": "Agent ID",
            "type": "string"
          },
          "groupId": {
            "description": "The unique identifier of the group",
            "title": "Group ID",
            "type": "string"
          }
        },
        "required": [
          "groupId",
          "agentId"
        ],
        "title": "AgentGroupAssignmentPostRequest",
        "type": "object"
      },
      "AgentGroupAssignmentPostResponse": {
        "properties": {
          "agent": {
            "$ref": "#/components/schemas/AgentGroupAssignmentPostAgent",
            "description": "The agent component of the agent group assignment",
            "title": "Agent"
          },
          "group": {
            "$ref": "#/components/schemas/AgentGroupAssignmentPostGroup",
            "description": "The group component of the agent group assignment",
            "title": "Group"
          },
          "id": {
            "description": "The unique identifier of the agent group assignment",
            "title": "ID",
            "type": "string"
          },
          "type": {
            "const": "networking-uxi/agent-group-assignment",
            "description": "The type of the resource.",
            "enum": [
              "networking-uxi/agent-group-assignment"
            ],
            "title": "Type",
            "type": "string"
          }
        },
        "required": [
          "id",
          "group",
          "agent",
          "type"
        ],
        "title": "AgentGroupAssignmentPostResponse",
        "type": "object"
      },
      "AgentGroupAssignmentsGetAgent": {
        "properties": {
          "id": {
            "description": "The unique identifier of the agent",
            "title": "Agent ID",
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "title": "AgentGroupAssignmentsGetAgent",
        "type": "object"
      },
      "AgentGroupAssignmentsGetGroup": {
        "properties": {
          "id": {
            "description": "The unique identifier of the group",
            "title": "Group ID",
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "title": "AgentGroupAssignmentsGetGroup",
        "type": "object"
      },
      "AgentGroupAssignmentsGetItem": {
        "properties": {
          "agent": {
            "$ref": "#/components/schemas/AgentGroupAssignmentsGetAgent",
            "description": "The agent component of the agent group assignment",
            "title": "Agent"
          },
          "group": {
            "$ref": "#/components/schemas/AgentGroupAssignmentsGetGroup",
            "description": "The group component of the agent group assignment",
            "title": "Group"
          },
          "id": {
            "description": "The unique identifier of the agent group assignment",
            "title": "ID",
            "type": "string"
          },
          "type": {
            "const": "networking-uxi/agent-group-assignment",
            "description": "The type of the resource.",
            "enum": [
              "networking-uxi/agent-group-assignment"
            ],
            "title": "Type",
            "type": "string"
          }
        },
        "required": [
          "id",
          "group",
          "agent",
          "type"
        ],
        "title": "AgentGroupAssignmentsGetItem",
        "type": "object"
      },
      "AgentGroupAssignmentsGetResponse": {
        "properties": {
          "count": {
            "description": "The number of resources returned in the response.",
            "title": "Count",
            "type": "integer"
          },
          "items": {
            "description": "The list of resources.",
            "items": {
              "$ref": "#/components/schemas/AgentGroupAssignmentsGetItem"
            },
            "title": "Items",
            "type": "array"
          },
          "next": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "description": "The next cursor for pagination.",
            "title": "Next"
          }
        },
        "required": [
          "items",
          "count",
          "next"
        ],
        "title": "AgentGroupAssignmentsGetResponse",
        "type": "object"
      },
      "ErrorDetail": {
        "properties": {
          "issues": {
            "items": {
              "$ref": "#/components/schemas/Issue"
            },
            "title": "Issues",
            "type": "array"
          },
          "type": {
            "title": "Type",
            "type": "string"
          }
        },
        "required": [
          "issues",
          "type"
        ],
        "title": "ErrorDetail",
        "type": "object"
      },
      "ErrorResponse": {
        "properties": {
          "debugId": {
            "title": "DebugID",
            "type": "string"
          },
          "errorCode": {
            "title": "ErrorCode",
            "type": "string"
          },
          "errorDetails": {
            "items": {
              "$ref": "#/components/schemas/ErrorDetail"
            },
            "title": "ErrorDetails",
            "type": "array"
          },
          "httpStatusCode": {
            "title": "HttpStatusCode",
            "type": "integer"
          },
          "message": {
            "title": "Message",
            "type": "string"
          }
        },
        "required": [
          "debugId",
          "errorCode",
          "httpStatusCode",
          "message"
        ],
        "title": "ErrorResponse",
        "type": "object"
      },
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "title": "Detail",
            "type": "array"
          }
        },
        "title": "HTTPValidationError",
        "type": "object"
      },
      "Issue": {
        "properties": {
          "description": {
            "title": "Description",
            "type": "string"
          },
          "source": {
            "title": "Source",
            "type": "string"
          },
          "subject": {
            "$ref": "#/components/schemas/IssueSubject"
          }
        },
        "required": [
          "description",
          "subject",
          "source"
        ],
        "title": "Issue",
        "type": "object"
      },
      "IssueSubject": {
        "enum": [
          "field",
          "header",
          "query.parameter"
        ],
        "title": "IssueSubject",
        "type": "string"
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "title": "Location",
            "type": "array"
          },
          "msg": {
            "title": "Message",
            "type": "string"
          },
          "type": {
            "title": "Error Type",
            "type": "string"
          }
        },
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError",
        "type": "object"
      }
    },
    "securitySchemes": {
      "HTTPBearer": {
        "type": "http",
        "scheme": "bearer",
        "description": "UXI REST API. Authorization: Bearer <access_token>"
      }
    }
  }
}
