{
  "openapi": "3.1.0",
  "info": {
    "title": "Orgs Admins",
    "version": "2602.1.1"
  },
  "servers": [
    {
      "description": "Mist Global 01",
      "url": "https://api.mist.com"
    },
    {
      "description": "Mist Global 02",
      "url": "https://api.gc1.mist.com"
    },
    {
      "description": "Mist Global 03",
      "url": "https://api.ac2.mist.com"
    },
    {
      "description": "Mist Global 04",
      "url": "https://api.gc2.mist.com"
    },
    {
      "description": "Mist Global 05",
      "url": "https://api.gc4.mist.com"
    },
    {
      "description": "Mist EMEA 01",
      "url": "https://api.eu.mist.com"
    },
    {
      "description": "Mist EMEA 02",
      "url": "https://api.gc3.mist.com"
    },
    {
      "description": "Mist EMEA 03",
      "url": "https://api.ac6.mist.com"
    },
    {
      "description": "Mist EMEA 04",
      "url": "https://api.gc6.mist.com"
    },
    {
      "description": "Mist APAC 01",
      "url": "https://api.ac5.mist.com"
    },
    {
      "description": "Mist APAC 02",
      "url": "https://api.gc5.mist.com"
    },
    {
      "description": "Mist APAC 03",
      "url": "https://api.gc7.mist.com"
    }
  ],
  "security": [
    {
      "apiToken": []
    },
    {
      "basicAuth": []
    },
    {
      "basicAuth": [],
      "csrfToken": []
    }
  ],
  "tags": [
    {
      "description": "An org admin, or organization administrator, is a user with administrative privileges within a specific organization. They have the authority to manage and oversee the operations and settings of that organization's portal.\n\n The different types of access levels for an org admin include:\n * Super User: This role has full access to the MSP portal and all tenant organizations. A super user can manage other administrators and has the highest level of privileges.\n * Network Admin: A network admin has limited access to the MSP portal. They can be granted access to all organizations or specific organizations, with access to limited features in the organizations' portals. They are responsible for monitoring, verifying, and troubleshooting the network within their assigned organizations.\n * Observer: An observer has view-only access to limited features in the MSP portal. They can be granted access to all organizations or specific organizations, with view-only access to limited features in the organizations' portals. Observers monitor events in the network and bring any issues to the attention of the network administrator for resolution.\n * Installer: An installer can be granted access to all organizations or specific organizations, with only the ability to install access points for these organizations. They are responsible for setting up and installing access points in the network.\n * Helpdesk: A helpdesk user can be granted access to all organizations or specific organizations, with only helpdesk monitoring and workflow capabilities for these organizations. They assist with monitoring and resolving issues reported by users within the organization.\n\n These different access levels allow org admins to perform their specific roles and responsibilities within the MSP portal while ensuring appropriate access and security measures are in place.",
      "name": "Orgs Admins"
    }
  ],
  "paths": {
    "/api/v1/orgs/{org_id}/admins": {
      "parameters": [
        {
          "$ref": "#/components/parameters/org_id"
        }
      ],
      "get": {
        "description": "Get List of people who can manage the Site/Org under the Org",
        "operationId": "listOrgAdmins",
        "responses": {
          "200": {
            "$ref": "#/components/responses/AdminsArray"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "listOrgAdmins",
        "tags": [
          "Orgs Admins"
        ]
      }
    },
    "/api/v1/orgs/{org_id}/admins/{admin_id}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/org_id"
        },
        {
          "$ref": "#/components/parameters/admin_id"
        }
      ],
      "put": {
        "description": "Invite Org Admin",
        "operationId": "updateOrgAdmin",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "email": "jsnow@abc.com",
                    "expire_time": 0,
                    "first_name": "John",
                    "hours": 24,
                    "last_name": "Sno",
                    "phone": "string",
                    "phone2": "string",
                    "privileges": [
                      {
                        "msp_id": "c0cf23fc-d82f-4219-988c-82fb61d8c875",
                        "name": "string",
                        "org_id": "a40f5d1f-d889-42e9-94ea-b9b33585fc6b",
                        "org_name": "string",
                        "orggroup_ids": [
                          "497f6eca-6276-4993-bfeb-53d5bbba6f08"
                        ],
                        "role": "admin",
                        "scope": "org",
                        "site_id": "72771e6a-6f5e-4de4-a5b9-1266c4197811",
                        "sitegroup_ids": [
                          "497f6eca-6276-4993-bfeb-53d6bbba6f08"
                        ],
                        "views": [
                          "switch_admin"
                        ]
                      }
                    ]
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/admin"
              }
            }
          },
          "description": "Request Body"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Admin"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "updateOrgAdmin",
        "tags": [
          "Orgs Admins"
        ]
      },
      "delete": {
        "description": "This removes all privileges this admin has against the org",
        "operationId": "revokeOrgAdmin",
        "responses": {
          "200": {
            "$ref": "#/components/responses/OK"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "revokeOrgAdmin",
        "tags": [
          "Orgs Admins"
        ]
      }
    },
    "/api/v1/orgs/{org_id}/invites": {
      "parameters": [
        {
          "$ref": "#/components/parameters/org_id"
        }
      ],
      "post": {
        "description": "If the request is successful, an email will also be sent to the user with a link to ```https://manage.mist.com/verify/invite?token=:token&expire=1459632743&org=OrgName```",
        "operationId": "inviteOrgAdmin",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "email": "user@example.com",
                    "first_name": "string",
                    "last_name": "string",
                    "privileges": [
                      {
                        "msp_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                        "msp_name": "string",
                        "name": "string",
                        "org_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                        "org_name": "string",
                        "orggroup_ids": [
                          "b069b358-4c97-5319-1f8c-7c5ca64d6ab1"
                        ],
                        "role": "admin",
                        "scope": "org",
                        "site_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                        "sitegroup_ids": [
                          "b069b358-4c97-5319-1f8c-7c5ca64d6ab1"
                        ]
                      }
                    ]
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/admin"
              }
            }
          },
          "description": "Request Body"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/OK"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "inviteOrgAdmin",
        "tags": [
          "Orgs Admins"
        ]
      }
    },
    "/api/v1/orgs/{org_id}/invites/{invite_id}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/org_id"
        },
        {
          "$ref": "#/components/parameters/invite_id"
        }
      ],
      "put": {
        "description": "Update Admin Invite",
        "operationId": "updateOrgAdminInvite",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "email": "user@example.com",
                    "first_name": "string",
                    "last_name": "string",
                    "privileges": [
                      {
                        "msp_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                        "msp_name": "string",
                        "name": "string",
                        "org_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                        "org_name": "string",
                        "orggroup_ids": [
                          "b069b358-4c97-5319-1f8c-7c5ca64d6ab1"
                        ],
                        "role": "admin",
                        "scope": "org",
                        "site_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                        "sitegroup_ids": [
                          "b069b358-4c97-5319-1f8c-7c5ca64d6ab1"
                        ]
                      }
                    ]
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/admin"
              }
            }
          },
          "description": "Request Body"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/OK"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "updateOrgAdminInvite",
        "tags": [
          "Orgs Admins"
        ]
      },
      "delete": {
        "description": "Delete Admin Invite",
        "operationId": "uninviteOrgAdmin",
        "responses": {
          "200": {
            "$ref": "#/components/responses/OK"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "uninviteOrgAdmin",
        "tags": [
          "Orgs Admins"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "admin": {
        "properties": {
          "admin_id": {
            "$ref": "#/components/schemas/admin_id"
          },
          "compliance_status": {
            "$ref": "#/components/schemas/admin_compliance_status"
          },
          "email": {
            "description": "If admin account is not an Org API Token",
            "examples": [
              "jsnow@abc.com"
            ],
            "format": "email",
            "type": "string"
          },
          "enable_two_factor": {
            "description": "If admin account is not an Org API Token",
            "readOnly": true,
            "type": "boolean"
          },
          "expire_time": {
            "type": "integer"
          },
          "first_name": {
            "description": "If admin account is not an Org API Token. For an invite, this is the original first name used",
            "examples": [
              "John"
            ],
            "type": "string"
          },
          "hours": {
            "default": 24,
            "description": "If admin account is not an Org API Token, how long the invite should be valid",
            "maximum": 168,
            "minimum": 1,
            "type": "integer"
          },
          "last_name": {
            "description": "If admin account is not an Org API Token. For an invite, this is the original last name used",
            "examples": [
              "Sno"
            ],
            "type": "string"
          },
          "name": {
            "description": "For Org API Token Only",
            "type": "string"
          },
          "no_tracking": {
            "default": null,
            "description": "Optional, whether to store privacy-consent information. When it doesn’t exist, it’s assumed true on EU (i.e. no tracking, the user has to opt-in); otherwise, the user would have to opt-out",
            "type": [
              "boolean",
              "null"
            ]
          },
          "oauth_google": {
            "description": "If admin account is not an Org API Token",
            "readOnly": true,
            "type": "boolean"
          },
          "password_modified_time": {
            "description": "Password last modified time, in epoch",
            "format": "double",
            "type": "number"
          },
          "phone": {
            "description": "If admin account is not an Org API Token. Phone number (numbers only, including country code)",
            "type": "string"
          },
          "phone2": {
            "description": "If admin account is not an Org API Token. Secondary phone number (numbers only, including country code)",
            "type": "string"
          },
          "privileges": {
            "$ref": "#/components/schemas/admin_privileges"
          },
          "session_expiry": {
            "examples": [
              1440
            ],
            "format": "int64",
            "maximum": 20160,
            "minimum": 10,
            "readOnly": true,
            "type": "integer"
          },
          "tags": {
            "$ref": "#/components/schemas/admin_tags"
          },
          "two_factor_verified": {
            "description": "If admin account is not an Org API Token. Two factor status",
            "readOnly": true,
            "type": "boolean"
          },
          "via_sso": {
            "description": "If admin account is not an Org API Token, an admin login via_sso is more restircted. (password and email cannot be changed)",
            "readOnly": true,
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "admin_compliance_status": {
        "description": "trade compliance status. enum: `blocked`, `restricted`",
        "enum": [
          "blocked",
          "restricted"
        ],
        "type": "string"
      },
      "admin_id": {
        "description": "ID of the administrator",
        "examples": [
          "456b7016-a916-a4b1-78dd-72b947c152b7"
        ],
        "format": "uuid",
        "readOnly": true,
        "type": "string"
      },
      "admin_privilege": {
        "additionalProperties": false,
        "description": "Privilieges settings",
        "properties": {
          "msp_id": {
            "$ref": "#/components/schemas/admin_privilege_msp_id"
          },
          "msp_logo_url": {
            "description": "Logo of the MSP (if the MSP belongs to an Advanced tier)",
            "readOnly": true,
            "type": "string"
          },
          "msp_name": {
            "description": "Name of the MSP (if the org belongs to an MSP)",
            "readOnly": true,
            "type": [
              "string",
              "null"
            ]
          },
          "msp_url": {
            "description": "Custom url of the MSP (if the MSP belongs to an Advanced tier)",
            "readOnly": true,
            "type": "string"
          },
          "name": {
            "description": "Name of the org/site/MSP depending on object scope",
            "readOnly": true,
            "type": "string"
          },
          "org_id": {
            "$ref": "#/components/schemas/admin_privilege_org_id"
          },
          "org_name": {
            "description": "Name of the org (for a site belonging to org)",
            "readOnly": true,
            "type": "string"
          },
          "orggroup_ids": {
            "$ref": "#/components/schemas/admin_privilege_orggroup_ids"
          },
          "role": {
            "$ref": "#/components/schemas/admin_privilege_role"
          },
          "scope": {
            "$ref": "#/components/schemas/admin_privilege_scope"
          },
          "site_id": {
            "$ref": "#/components/schemas/admin_privilege_site_id"
          },
          "sitegroup_ids": {
            "$ref": "#/components/schemas/admin_privilege_sitegroup_ids"
          },
          "views": {
            "$ref": "#/components/schemas/admin_privilege_views"
          }
        },
        "required": [
          "role",
          "scope"
        ],
        "type": "object"
      },
      "admin_privilege_msp_id": {
        "description": "Required if `scope`==`msp`",
        "examples": [
          "b9d42c2e-88ee-41f8-b798-f009ce7fe909"
        ],
        "format": "uuid",
        "type": "string"
      },
      "admin_privilege_org_id": {
        "description": "Required if `scope`==`org`",
        "examples": [
          "a97c1b22-a4e9-411e-9bfd-d8695a0f9e61"
        ],
        "format": "uuid",
        "type": "string"
      },
      "admin_privilege_orggroup_ids": {
        "description": "If `scope`==`orggroup`",
        "items": {
          "$ref": "#/components/schemas/orggroup_id"
        },
        "type": "array"
      },
      "admin_privilege_role": {
        "description": "access permissions. enum: `admin`, `helpdesk`, `installer`, `read`, `write`",
        "enum": [
          "admin",
          "helpdesk",
          "installer",
          "read",
          "write"
        ],
        "type": "string"
      },
      "admin_privilege_scope": {
        "description": "enum: `msp`, `org`, `orggroup`, `site`, `sitegroup`",
        "enum": [
          "msp",
          "org",
          "orggroup",
          "site",
          "sitegroup"
        ],
        "type": "string"
      },
      "admin_privilege_site_id": {
        "description": "Required if `scope`==`site`",
        "examples": [
          "441a1214-6928-442a-8e92-e1d34b8ec6a6"
        ],
        "format": "uuid",
        "type": "string"
      },
      "admin_privilege_sitegroup_ids": {
        "items": {
          "$ref": "#/components/schemas/sitegroup_id"
        },
        "type": "array"
      },
      "admin_privilege_view": {
        "enum": [
          "lobby_admin",
          "location",
          "marketing",
          "mxedge_admin",
          "reporting",
          "security",
          "super_observer",
          "switch_admin"
        ],
        "type": "string"
      },
      "admin_privilege_views": {
        "description": "Custom roles restrict Org users to specific UI views. This is useful for limiting UI access of Org users. Custom roles restrict Org users to specific UI views. This is useful for limiting UI access of Org users.  \nYou can define custom roles by adding the `views` attribute along with `role` when assigning privileges.  \nBelow are the list of supported UI views. Note that this is UI only feature.  \n\n  | UI View | Required Role | Description |\n  | --- | --- | --- |\n  | `reporting` | `read` | full access to all analytics tools |\n  | `marketing` | `read` | can view analytics and location maps |\n  | `super_observer` | `read` | can view all the organization except the subscription page |\n  | `location` | `write` | can view and manage location maps, can view analytics |\n  | `security` | `write` | can view and manage site labels, policies and security |\n  | `switch_admin` | `helpdesk` | can view and manage Switch ports, can view wired clients |\n  | `mxedge_admin` | `admin` | can view and manage Mist edges and Mist tunnels |\n  | `lobby_admin` | `admin` | full access to Org and Site Pre-shared keys |",
        "items": {
          "$ref": "#/components/schemas/admin_privilege_view"
        },
        "type": "array"
      },
      "admin_privileges": {
        "description": "List of privileges the admin has",
        "items": {
          "$ref": "#/components/schemas/admin_privilege"
        },
        "minItems": 1,
        "type": "array",
        "uniqueItems": true
      },
      "admin_tags": {
        "items": {
          "type": "string"
        },
        "readOnly": true,
        "type": "array"
      },
      "admins": {
        "items": {
          "$ref": "#/components/schemas/admin"
        },
        "type": "array",
        "uniqueItems": true
      },
      "orggroup_id": {
        "examples": [
          "832b1d74-9531-409b-ae37-4d7f3edbde92"
        ],
        "format": "uuid",
        "type": "string"
      },
      "response_http400": {
        "additionalProperties": false,
        "properties": {
          "detail": {
            "examples": [
              "JSON parse error - Expecting value: line 5 column 8 (char 56)"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "response_http401": {
        "additionalProperties": false,
        "properties": {
          "detail": {
            "examples": [
              "Authentication credentials were not provided."
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "response_http403": {
        "additionalProperties": false,
        "properties": {
          "detail": {
            "examples": [
              "You do not have permission to perform this action."
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "response_http404": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "response_http429": {
        "additionalProperties": false,
        "properties": {
          "detail": {
            "examples": [
              "Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "sitegroup_id": {
        "examples": [
          "3c708be3-9422-4695-b729-babdbd2f7615"
        ],
        "format": "uuid",
        "type": "string"
      }
    },
    "responses": {
      "Admin": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/AdminExample"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/admin"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/AdminExample"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/admin"
            }
          }
        },
        "description": "OK"
      },
      "AdminsArray": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/AdminsArrayExample"
              },
              "Example2": {
                "$ref": "#/components/examples/AdminsArrayExample2"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/admins"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/AdminsArrayExample"
              },
              "Example2": {
                "$ref": "#/components/examples/AdminsArrayExample2"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/admins"
            }
          }
        },
        "description": "OK"
      },
      "HTTP400": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP400Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http400"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP400Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http400"
            }
          }
        },
        "description": "Bad Syntax"
      },
      "HTTP401": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP401Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http401"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP401Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http401"
            }
          }
        },
        "description": "Unauthorized"
      },
      "HTTP403": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP403Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http403"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP403Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http403"
            }
          }
        },
        "description": "Permission Denied"
      },
      "HTTP404": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/response_http404"
            }
          },
          "application/vnd.api+json": {
            "schema": {
              "$ref": "#/components/schemas/response_http404"
            }
          }
        },
        "description": "Not found. The API endpoint doesn’t exist or resource doesn’ t exist"
      },
      "HTTP429": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP429Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http429"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP429Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http429"
            }
          }
        },
        "description": "Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold"
      },
      "OK": {
        "description": "OK"
      }
    },
    "parameters": {
      "admin_id": {
        "in": "path",
        "name": "admin_id",
        "required": true,
        "schema": {
          "examples": [
            "000000ab-00ab-00ab-00ab-0000000000ab"
          ],
          "format": "uuid",
          "type": "string"
        }
      },
      "invite_id": {
        "in": "path",
        "name": "invite_id",
        "required": true,
        "schema": {
          "examples": [
            "000000ab-00ab-00ab-00ab-0000000000ab"
          ],
          "format": "uuid",
          "type": "string"
        }
      },
      "org_id": {
        "in": "path",
        "name": "org_id",
        "required": true,
        "schema": {
          "examples": [
            "000000ab-00ab-00ab-00ab-0000000000ab"
          ],
          "format": "uuid",
          "type": "string"
        }
      }
    },
    "examples": {
      "AdminExample": {
        "value": {
          "admin_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
          "email": "user@example.com",
          "first_name": "string",
          "last_name": "string",
          "password_modified_time": 1656353525,
          "privileges": [
            {
              "msp_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
              "msp_name": "string",
              "name": "string",
              "org_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
              "org_name": "string",
              "orggroup_ids": [
                "b069b358-4c97-5319-1f8c-7c5ca64d6ab1"
              ],
              "role": "admin",
              "scope": "org",
              "site_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
              "sitegroup_ids": [
                "6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9"
              ]
            }
          ]
        }
      },
      "AdminsArrayExample": {
        "value": [
          {
            "admin_id": "456b7016-a916-a4b1-78dd-72b947c152b7",
            "email": "jsmith@mycorp.org",
            "first_name": "Joe",
            "last_name": "Smith",
            "privileges": [
              {
                "role": "admin",
                "scope": "msp"
              },
              {
                "org_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                "role": "admin",
                "scope": "org"
              },
              {
                "orggroup_ids": [
                  "507f1bab-13ba-73e2-f291-2bcb8d1362b0"
                ],
                "role": "read",
                "scope": "orggroup"
              }
            ]
          }
        ]
      },
      "AdminsArrayExample2": {
        "value": [
          {
            "admin_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
            "email": "user@example.com",
            "first_name": "string",
            "last_name": "string",
            "privileges": [
              {
                "msp_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                "msp_name": "string",
                "name": "string",
                "org_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                "org_name": "string",
                "orggroup_ids": [
                  "b069b358-4c97-5319-1f8c-7c5ca64d6ab1"
                ],
                "role": "admin",
                "scope": "org",
                "site_id": "b069b358-4c97-5319-1f8c-7c5ca64d6ab1",
                "sitegroup_ids": [
                  "6f4bf402-45f9-2a56-6c8b-7f83d3bc98e9"
                ]
              }
            ]
          }
        ]
      },
      "HTTP400Example": {
        "value": {
          "detail": "JSON parse error - Expecting value: line 5 column 8 (char 56)"
        }
      },
      "HTTP401Example": {
        "value": {
          "detail": "Authentication credentials were not provided."
        }
      },
      "HTTP403Example": {
        "value": {
          "detail": "You do not have permission to perform this action."
        }
      },
      "HTTP429Example": {
        "value": {
          "detail": "Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold"
        }
      }
    },
    "securitySchemes": {
      "apiToken": {
        "description": "Like many other API providers, it’s also possible to generate API Tokens to be used (in HTTP Header) for authentication. An API token ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated for a specific admin has the same privilege as the user\n* an API token will be automatically removed if not used for > 90 days\n* SSO admins cannot generate these API tokens. Refer Org level API tokens which can have privileges of a specific Org/Site for more information.",
        "in": "header",
        "name": "Authorization",
        "type": "apiKey",
        "x-scalar-secret-token": "Token YOUR_API_TOKEN"
      },
      "basicAuth": {
        "description": "While our current UI uses Session / Cookie-based authentication, it’s also possible to do Basic Auth.",
        "scheme": "basic",
        "type": "http"
      },
      "csrfToken": {
        "description": "This protects the website against [Cross Site Request Forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery), all the POST / PUT / DELETE APIs needs to have CSRF token in the AJAX Request header when using Login/Password authentication (with or without MFA)\n\n\nThe CSRF Token is sent back by Mist in the Cookies from the Login Response API Call:\n`cookies[csrftoken]` \n\nThe CSRF Token must be added in the HTTP Request Headers:\n```\nX-CSRFToken: vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx\n```",
        "in": "header",
        "name": "X-CSRFToken",
        "type": "apiKey"
      }
    }
  }
}
