{
  "openapi": "3.1.0",
  "info": {
    "title": "Utilities WAN",
    "version": "2602.1.1"
  },
  "servers": [
    {
      "description": "Mist Global 01",
      "url": "https://api.mist.com"
    },
    {
      "description": "Mist Global 02",
      "url": "https://api.gc1.mist.com"
    },
    {
      "description": "Mist Global 03",
      "url": "https://api.ac2.mist.com"
    },
    {
      "description": "Mist Global 04",
      "url": "https://api.gc2.mist.com"
    },
    {
      "description": "Mist Global 05",
      "url": "https://api.gc4.mist.com"
    },
    {
      "description": "Mist EMEA 01",
      "url": "https://api.eu.mist.com"
    },
    {
      "description": "Mist EMEA 02",
      "url": "https://api.gc3.mist.com"
    },
    {
      "description": "Mist EMEA 03",
      "url": "https://api.ac6.mist.com"
    },
    {
      "description": "Mist EMEA 04",
      "url": "https://api.gc6.mist.com"
    },
    {
      "description": "Mist APAC 01",
      "url": "https://api.ac5.mist.com"
    },
    {
      "description": "Mist APAC 02",
      "url": "https://api.gc5.mist.com"
    },
    {
      "description": "Mist APAC 03",
      "url": "https://api.gc7.mist.com"
    }
  ],
  "security": [
    {
      "apiToken": []
    },
    {
      "basicAuth": []
    },
    {
      "basicAuth": [],
      "csrfToken": []
    }
  ],
  "tags": [
    {
      "description": "API Calls to use Devices Troubleshooting tools specific to WAN Assurance",
      "name": "Utilities WAN"
    }
  ],
  "paths": {
    "/api/v1/sites/{site_id}/devices/{device_id}/clear_arp": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Clear ARP cache for SSR, SRX and Switch\n\nClear the entire ARP cache or a subset if arguments are provided.\n\n*Note*: port_id is optional if neither vlan nor ip is specified",
        "operationId": "clearSiteSsrArpCache",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/utils_clear_arp"
              }
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "clearSiteSsrArpCache",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/clear_bgp": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Clear routes associated with one or all BGP neighbors",
        "operationId": "clearSiteSsrBgpRoutes",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "neighbor": "all",
                    "type": "in",
                    "vrf": "TestVrf"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/utils_clear_bgp"
              }
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "description": "Parameter neighbor absent"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "clearSiteBgpRoutes",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/clear_session": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Clear session",
        "operationId": "clearSiteDeviceSession",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "port_id": "ge-0/0/1.10"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/utils_clear_session"
              }
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/OK"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "clearSiteDeviceSession",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/release_dhcp": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Releases an active DHCP lease.\n\nThe output will be available through websocket. As there can be multiple command issued  against the same Device at the same time and the output all goes through the same websocket stream, session is introduced for demux.\n\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n    \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}```\n\n\n\n#### Example output from ws stream\n\n```json\n{  \n  \"channel\": \"/sites/d6fb4f96-xxxx-xxxx-xxxx-xxxxxxxxxxxx/devices/00000000-0000-0000-1000-xxxxxxxxxxxx/cmd\",\n  \"event\": \"data\",\n  \"data\": {\n    \"session\": \"9106e908-74dc-4a4f-9050-9c2adcaf44a5\",\n    \"raw\": \"Running traceroute...\\ntraceroute to 8.8.8.8, 64 hops max\\n 0  192.168.1.1 1 ms  192.168.1.1 1 ms  192.168.1.1 1 ms\\n 1  80.10.236.81 2 ms  80.10.236.81 4 ms  80.10.236.81 2 ms\\n 2  193.253.80.250 3 ms  193.253.80.250 2 ms  193.253.80.250 2 ms\\n 3  193.252.159.41 2 ms  193.252.159.41 1 ms  193.252.159.41 3 ms\\n\"\n  }\n}\n```\n\"",
        "operationId": "releaseSiteSsrDhcpLease",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "port_id": "ge-0/0/1.10"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/utils_release_dhcp"
              }
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "description": "Parameter `port ` absent"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "releaseSiteSsrDhcpLease",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/resolve_dns": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "DNS resolutions are performed on the Device.\n\nThe output will be available through websocket. As there can be multiple command issued against the same SSR at the same time and the output all goes through the same websocket stream, `session` is used for demux.\n \n #### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n    \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}\n```\n##### Example output from ws stream\n```\n Router      | Hostname               | Resolved | Last Resolved        | Expiration\n-------------|------------------------|----------|----------------------|---------------------\n test-device | xxx.yyy.net            | Y        | 2022-03-28T03:56:49Z | 2022-03-28T03:57:49Z\n```",
        "operationId": "testSiteSsrDnsResolution",
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "testSiteSsrDnsResolution",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/run_top": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Run top command on switches and SRX. The output will be available through websocket. \n\nAs there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, `session` is introduced for demux.\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n  \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}\n```",
        "operationId": "runSiteSrxTopCommand",
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSessionWithUrl"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "runSiteSrxTopCommand",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/service_ping": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Ping from SSR\n\nService Ping can be performed from the Device. The output will be available through websocket. As there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, session is introduced for demux.\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n    \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}\n```\n##### Example output from ws stream\n```json\n{\n    \"event\": \"data\",\n    \"channel\": \"/sites/4ac1dcf4-9d8b-7211-65c4-057819f0862b/devices/00000000-0000-0000-1000-5c5b350e0060/cmd\",\n    \"data\": {\n        \"session\": \"session_id\",\n        \"raw\": \"64 bytes from 23.211.0.110: seq=8 ttl=58 time=12.323 ms\\n\"\n    }\n}\n```",
        "operationId": "servicePingFromSsr",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "count": 10,
                    "host": "1.1.1.1",
                    "service": "web-session"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/utils_service_ping"
              }
            }
          },
          "description": "Request Body"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "servicePingFromSsr",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/show_ospf_database": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Get OSPF Database from SSR and SRX. The output will be available through websocket. \n\nAs there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, `session` is introduced for demux.\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n  \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}\n```\n\n#### Example output from ws stream\n```\n===== ==================== ========== ======= ======== ================ =================== =================\nVrf   Neighbor Router ID   Priority   State   Uptime   Dead Timer Due   Interface Address   Interface State\n===== ==================== ========== ======= ======== ================ =================== =================\n      1.0.0.3                     1   Full       852               38   172.16.3.2          Backup\n      1.0.0.4                     1   Full       811               33   172.16.3.2          DROther\n      1.0.0.3                     1   Full       852               38   172.16.4.2          Backup\n      1.0.0.4                     1   Full       811               34   172.16.4.2          DROther\n```",
        "operationId": "showSiteGatewayOspfDatabase",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/utils_show_ospf_database"
              }
            }
          },
          "description": "All attributes are optional"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "showSiteGatewayOspfDatabase",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/show_ospf_interfaces": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Get OSPF interfaces from SSR and SRX. The output will be available through websocket. \n\nAs there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, `session` is introduced for demux.\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n  \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}\n```\n\n#### Example output from ws stream\n```\n===== ================== =================== ============== =============== =========== ========= ===========\nVrf   Device Interface   Network Interface   Interface Up   IP Address      OSPF Type   Area ID   Area Type\n===== ================== =================== ============== =============== =========== ========= ===========\n      net1               g1                          True   172.16.1.2/24   Broadcast   0.0.0.0   default\n      net3               g3                          True   172.16.3.2/24   Broadcast   0.0.0.0   default\n      net4               g4                          True   172.16.4.2/24   Broadcast   0.0.0.4   default\n```",
        "operationId": "showSiteGatewayOspfInterfaces",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/utils_show_ospf_interfaces"
              }
            }
          },
          "description": "All attributes are optional"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "showSiteGatewayOspfInterfaces",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/show_ospf_neighbors": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Get OSPF Neighbors from SSR and SRX. The output will be available through websocket. \n\nAs there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, `session` is introduced for demux.\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n  \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}\n```\n\n#### Example output from ws stream\n```\n===== ==================== ========== ======= ======== ================ =================== =================\nVrf   Neighbor Router ID   Priority   State   Uptime   Dead Timer Due   Interface Address   Interface State\n===== ==================== ========== ======= ======== ================ =================== =================\n      1.0.0.3                     1   Full       852               38   172.16.3.2          Backup\n      1.0.0.4                     1   Full       811               33   172.16.3.2          DROther\n      1.0.0.3                     1   Full       852               38   172.16.4.2          Backup\n      1.0.0.4                     1   Full       811               34   172.16.4.2          DROther\n```",
        "operationId": "showSiteGatewayOspfNeighbors",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/utils_show_ospf_neighbors"
              }
            }
          },
          "description": "All attributes are optional"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "showSiteGatewayOspfNeighbors",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/show_ospf_summary": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Get OSPF summary from SSR and SRX. The output will be available through websocket. \n\nAs there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, `session` is introduced for demux.\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n  \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}\n```\n\n#### Example output from ws stream\n```\n===== =========== ========== ============= ==================== ========= =========== =============\nVrf   Router ID   ABR Type   ASBR Router   External LSA Count   Area ID   Area Type   Area Border\n                                                                                      Router\n===== =========== ========== ============= ==================== ========= =========== =============\n      1.0.0.2     cisco            False                    0   0.0.0.0\n      1.0.0.2     cisco            False                    0   0.0.0.4   default\n```",
        "operationId": "showSiteGatewayOspfSummary",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/utils_show_ospf_summary"
              }
            }
          },
          "description": "All attributes are optional"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "showSiteGatewayOspfSummary",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/show_route": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Get routes from SSR, SRX and Switch. \n\nThe output will be available through websocket. As there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, `session` is introduced for demux.\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json\n{\n    \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\"\n}\n```\n##### Example output from ws stream\n```\nadmin@labsystem1.fiedler# show bgp neighbors\nBGP neighbor is 192.168.4.1, remote AS 4200000001, local AS 4200000128, external\nlink\n  BGP version 4, remote router ID 1.1.1.1\n  BGP state = Established, up for 00:27:25\n  Last read 00:00:25, hold time is 90, keepalive interval is 30 seconds\n  Configured hold time is 90, keepalive interval is 30 seconds\n  Neighbor capabilities:\n    4 Byte AS: advertised and received\n    Route refresh: advertised and received(old &amp; new)\n    Address family IPv4 Unicast: advertised and received\n    Graceful Restart Capability: advertised and received\n      Remote Restart timer is 120 seconds\n      Address families by peer:\n        none\n        ...\n```",
        "operationId": "showSiteSsrAndSrxRoutes",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/utils_show_route"
              }
            }
          },
          "description": "All attributes are optional"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "showSiteSsrAndSrxRoutes",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/show_service_path": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Get service path information of the Device.\n\nThe output will be available through websocket. As there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, session is introduced for demux.\n\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json { \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\" } ```\n#### Example output from ws stream\n```json { \"channel\": \"/sites/d6fb4f96-xxxx-xxxx-xxxx-xxxxxxxxxxxx/devices/00000000-0000-0000-1000-xxxxxxxxxxxx/cmd\", \"event\": \"data\", \"data\": { \"session\":\"5cb8a6db-d11a-42cd-bed7-19e9f29e637\", \"raw\":\"{\\\"status\\\":\\\"SUCCESS\\\",\\\"finished\\\":true,\\\"rows\\\":[{\\\"service\\\":\\\"management\\\",\\\"type\\\":\\\"service-agent\\\",\\\"network_interface\\\":\\\"ge-0/0/0\\\",\\\"destination\\\":\\\"\\\",\\\"gateway_ip\\\":\\\"192.168.1.1\\\",\\\"vector\\\":\\\"\\\",\\\"cost\\\":0,\\\"rate\\\":0,\\\"state\\\":\\\"Up\\\",\\\"capacity\\\":\\\"0/unlimited\\\",\\\"meetsSLA\\\":\\\"Yes\\\"},{\\\"service\\\":\\\"management\\\",\\\"type\\\":\\\"service-agent\\\",\\\"network_interface\\\":\\\"ge-0/0/1\\\",\\\"destination\\\":\\\"\\\",\\\"gateway_ip\\\":\\\"192.168.0.1\\\",\\\"vector\\\":\\\"\\\",\\\"cost\\\":0,\\\"rate\\\":0,\\\"state\\\":\\\"Up\\\",\\\"capacity\\\":\\\"0/unlimited\\\",\\\"meetsSLA\\\":\\\"Yes\\\"}]}\" } } ```",
        "operationId": "showSiteSsrServicePath",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "node": "node0",
                    "service_name": "any"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/utils_show_service_path"
              }
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "showSiteSsrServicePath",
        "tags": [
          "Utilities WAN"
        ]
      }
    },
    "/api/v1/sites/{site_id}/devices/{device_id}/show_session": {
      "parameters": [
        {
          "$ref": "#/components/parameters/site_id"
        },
        {
          "$ref": "#/components/parameters/device_id"
        }
      ],
      "post": {
        "description": "Get active sessions passing through the Device.\n\nThe output will be available through websocket. As there can be multiple command issued against the same device at the same time and the output all goes through the same websocket stream, session is introduced for demux.\n\n\n#### Subscribe to Device Command outputs\n`WS /api-ws/v1/stream`\n\n```json { \"subscribe\": \"/sites/{site_id}/devices/{device_id}/cmd\" }```\n\n#### Example output from ws stream\n```json { \"channel\": \"/sites/d6fb4f96-xxxx-xxxx-xxxx-xxxxxxxxxxxx/devices/00000000-0000-0000-1000-xxxxxxxxxxxx/cmd\", \"event\": \"data\", \"data\": { \"session\": \"f517bf29-1141-41ae-a084-17cacb0ccb57\", \"raw\": \"{\\\"status\\\":\\\"SUCCESS\\\",\\\"finished\\\":true,\\\"rows\\\":[{\\\"session_id\\\":\\\"a04b1cc7-dcc1-40a6-a010-0fe46ca38551\\\",\\\"direction\\\":\\\"forward\\\",\\\"service\\\":\\\"internet\\\",\\\"tenant\\\":\\\"SRV.PRD-Core\\\",\\\"device_interface\\\":\\\"ge-0/0/3\\\",\\\"network_interface\\\":\\\"ge-0/0/3.100\\\",\\\"protocol\\\":\\\"TCP\\\",\\\"source_ip\\\":\\\"10.3.20.101\\\",\\\"source_port\\\":45733,\\\"destination_ip\\\":\\\"13.38.46.35\\\",\\\"destination_port\\\":443,\\\"nat_ip\\\":\\\"192.168.1.115\\\",\\\"nat_port\\\":45256,\\\"payload_encrypted\\\":false,\\\"timeout\\\":1581,\\\"uptime\\\":319},{\\\"session_id\\\":\\\"a04b1cc7-dcc1-40a6-a010-0fe46ca38551\\\",\\\"direction\\\":\\\"reverse\\\",\\\"service\\\":\\\"internet\\\",\\\"tenant\\\":\\\"SRV.PRD-Core\\\",\\\"device_interface\\\":\\\"ge-0/0/0\\\",\\\"network_interface\\\":\\\"ge-0/0/0\\\",\\\"protocol\\\":\\\"TCP\\\",\\\"source_ip\\\":\\\"13.38.46.35\\\",\\\"source_port\\\":443,\\\"destination_ip\\\":\\\"192.168.1.115\\\",\\\"destination_port\\\":45256,\\\"nat_ip\\\":\\\"0.0.0.0\\\",\\\"nat_port\\\":0,\\\"payload_encrypted\\\":false,\\\"timeout\\\":1581,\\\"uptime\\\":319}]}\\n\" } } ```",
        "operationId": "showSiteSsrAndSrxSessions",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Example": {
                  "value": {
                    "node": "node0",
                    "service_name": "any"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/utils_show_session"
              }
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebsocketSession"
          },
          "400": {
            "$ref": "#/components/responses/HTTP400"
          },
          "401": {
            "$ref": "#/components/responses/HTTP401"
          },
          "403": {
            "$ref": "#/components/responses/HTTP403"
          },
          "404": {
            "$ref": "#/components/responses/HTTP404"
          },
          "429": {
            "$ref": "#/components/responses/HTTP429"
          }
        },
        "summary": "showSiteSsrAndSrxSessions",
        "tags": [
          "Utilities WAN"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "ha_cluster_node": {
        "properties": {
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          }
        },
        "type": "object"
      },
      "ha_cluster_node_enum": {
        "description": "only for HA. enum: `node0`, `node1`",
        "enum": [
          "node0",
          "node1"
        ],
        "type": "string"
      },
      "response_http400": {
        "additionalProperties": false,
        "properties": {
          "detail": {
            "examples": [
              "JSON parse error - Expecting value: line 5 column 8 (char 56)"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "response_http401": {
        "additionalProperties": false,
        "properties": {
          "detail": {
            "examples": [
              "Authentication credentials were not provided."
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "response_http403": {
        "additionalProperties": false,
        "properties": {
          "detail": {
            "examples": [
              "You do not have permission to perform this action."
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "response_http404": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "response_http429": {
        "additionalProperties": false,
        "properties": {
          "detail": {
            "examples": [
              "Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "utils_clear_arp": {
        "properties": {
          "ip": {
            "description": "The IP address for which to clear an ARP entry. port_id must be specified.",
            "examples": [
              "10.1.1.1"
            ],
            "type": "string"
          },
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "port_id": {
            "description": "The device interface on which to clear the ARP cache.",
            "examples": [
              "wan"
            ],
            "type": "string"
          },
          "vlan": {
            "description": "The VLAN on which to clear the ARP cache. port_id must be specified.",
            "examples": [
              1000
            ],
            "type": "integer"
          },
          "vrf": {
            "description": "The vrf for which to clear an ARP entry. applicable for switch.",
            "examples": [
              "guest"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "utils_clear_bgp": {
        "properties": {
          "neighbor": {
            "description": "Neighbor ip-address or 'all'",
            "type": "string"
          },
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "type": {
            "$ref": "#/components/schemas/utils_clear_bgp_type"
          },
          "vrf": {
            "description": "VRF name",
            "type": "string"
          }
        },
        "required": [
          "neighbor",
          "type"
        ],
        "type": "object"
      },
      "utils_clear_bgp_type": {
        "default": "hard",
        "description": "enum: `hard`, `in`, `out`, `soft`",
        "enum": [
          "hard",
          "in",
          "out",
          "soft"
        ],
        "type": "string"
      },
      "utils_clear_session": {
        "description": "To use five tuples to lookup the session to be cleared, all must be provided",
        "properties": {
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "service_name": {
            "description": "Service name, only supported in SSR",
            "examples": [
              "internet-wan_and_lte"
            ],
            "type": "string"
          },
          "session_ids": {
            "$ref": "#/components/schemas/utils_clear_session_session_ids"
          }
        },
        "type": "object"
      },
      "utils_clear_session_session_ids": {
        "description": "List of id of the sessions to be cleared",
        "examples": [
          [
            "88776655-0123-4567-890a-112233445566"
          ]
        ],
        "items": {
          "format": "uuid",
          "type": "string"
        },
        "type": "array"
      },
      "utils_release_dhcp": {
        "properties": {
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "port_id": {
            "description": "The network interface on which to release the current DHCP release",
            "examples": [
              "ge-0/0/1.10"
            ],
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "port_id"
        ],
        "type": "object"
      },
      "utils_service_ping": {
        "properties": {
          "count": {
            "default": 10,
            "type": "integer"
          },
          "host": {
            "format": "ipv4",
            "type": "string"
          },
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "service": {
            "description": "Ping packet takes the same path as the service",
            "type": "string"
          },
          "size": {
            "default": 56,
            "maximum": 65535,
            "minimum": 56,
            "type": "integer"
          },
          "tenant": {
            "description": "Tenant context in which the packet is sent",
            "type": "string"
          }
        },
        "required": [
          "host",
          "service"
        ],
        "type": "object"
      },
      "utils_show_ospf_database": {
        "properties": {
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "self_originate": {
            "default": false,
            "description": "Show originating info, default is false",
            "type": "boolean"
          },
          "vrf": {
            "description": "VRF name",
            "examples": [
              "lan"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "utils_show_ospf_interfaces": {
        "properties": {
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "port_id": {
            "description": "Network interface",
            "examples": [
              "ge-0/0/3"
            ],
            "type": "string"
          },
          "vrf": {
            "description": "VRF name",
            "examples": [
              "lan"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "utils_show_ospf_neighbors": {
        "properties": {
          "neighbor": {
            "description": "Neighbor IP Address",
            "examples": [
              "10.1.1.1"
            ],
            "type": "string"
          },
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "port_id": {
            "description": "Network interface",
            "examples": [
              "ge-0/0/3"
            ],
            "type": "string"
          },
          "vrf": {
            "description": "VRF name",
            "examples": [
              "lan"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "utils_show_ospf_summary": {
        "properties": {
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "vrf": {
            "description": "VRF name",
            "examples": [
              "lan"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "utils_show_route": {
        "properties": {
          "duration": {
            "default": 0,
            "description": "Duration in sec for which refresh is enabled. Should be set only if interval is configured to non-zero value.",
            "maximum": 300,
            "minimum": 0,
            "type": "integer"
          },
          "interval": {
            "default": 0,
            "description": "Rate at which output will refresh",
            "maximum": 10,
            "minimum": 0,
            "type": "integer"
          },
          "neighbor": {
            "description": "IP of the neighbor",
            "examples": [
              "192.168.4.1"
            ],
            "type": "string"
          },
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node"
          },
          "prefix": {
            "description": "Route prefix",
            "examples": [
              "192.168.0.5/30"
            ],
            "type": "string"
          },
          "protocol": {
            "$ref": "#/components/schemas/utils_show_route_protocol"
          },
          "route": {
            "description": "If specified, dump bot received and advertised, if not specified, both will be shown\n  * for SSR, show bgp neighbors 10.250.18.202 received-routes/advertised-routes\n  * for SRX and Switches, show route receive_protocol/advertise_protocol bgp 192.168.255.12'",
            "examples": [
              "advertised"
            ],
            "type": "string"
          },
          "vrf": {
            "description": "VRF name",
            "examples": [
              "default"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "utils_show_route_protocol": {
        "default": "bgp",
        "description": "enum: `any`, `bgp`, `direct`, `evpn`, `ospf`, `static`",
        "enum": [
          "any",
          "bgp",
          "direct",
          "evpn",
          "ospf",
          "static"
        ],
        "type": "string"
      },
      "utils_show_service_path": {
        "description": "The exact service name for which to display the service path",
        "properties": {
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "service_name": {
            "examples": [
              "any"
            ],
            "type": "string"
          }
        },
        "type": "object"
      },
      "utils_show_session": {
        "properties": {
          "node": {
            "$ref": "#/components/schemas/ha_cluster_node_enum"
          },
          "service_name": {
            "description": "The exact service name for which to display the active sessions",
            "examples": [
              "any"
            ],
            "type": "string"
          },
          "session_id": {
            "description": "Show session details by session_id",
            "type": "string"
          }
        },
        "type": "object"
      },
      "websocket_session": {
        "additionalProperties": false,
        "properties": {
          "session": {
            "examples": [
              "19e73828-937f-05e6-f709-e29efdb0a82b"
            ],
            "type": "string"
          }
        },
        "required": [
          "session"
        ],
        "type": "object"
      },
      "websocket_session_with_url": {
        "additionalProperties": false,
        "properties": {
          "session": {
            "examples": [
              "19e73828-937f-05e6-f709-e29efdb0a82b"
            ],
            "type": "string"
          },
          "url": {
            "examples": [
              "wss://api-ws.mist.com/ssh?jwt=xxxx"
            ],
            "type": "string"
          }
        },
        "required": [
          "session",
          "url"
        ],
        "type": "object"
      }
    },
    "responses": {
      "HTTP400": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP400Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http400"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP400Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http400"
            }
          }
        },
        "description": "Bad Syntax"
      },
      "HTTP401": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP401Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http401"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP401Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http401"
            }
          }
        },
        "description": "Unauthorized"
      },
      "HTTP403": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP403Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http403"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP403Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http403"
            }
          }
        },
        "description": "Permission Denied"
      },
      "HTTP404": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/response_http404"
            }
          },
          "application/vnd.api+json": {
            "schema": {
              "$ref": "#/components/schemas/response_http404"
            }
          }
        },
        "description": "Not found. The API endpoint doesn’t exist or resource doesn’ t exist"
      },
      "HTTP429": {
        "content": {
          "application/json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP429Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http429"
            }
          },
          "application/vnd.api+json": {
            "examples": {
              "Example": {
                "$ref": "#/components/examples/HTTP429Example"
              }
            },
            "schema": {
              "$ref": "#/components/schemas/response_http429"
            }
          }
        },
        "description": "Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold"
      },
      "OK": {
        "description": "OK"
      },
      "WebsocketSession": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/websocket_session"
            }
          },
          "application/vnd.api+json": {
            "schema": {
              "$ref": "#/components/schemas/websocket_session"
            }
          }
        },
        "description": "OK"
      },
      "WebsocketSessionWithUrl": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/websocket_session_with_url"
            }
          },
          "application/vnd.api+json": {
            "schema": {
              "$ref": "#/components/schemas/websocket_session_with_url"
            }
          }
        },
        "description": "OK"
      }
    },
    "parameters": {
      "device_id": {
        "in": "path",
        "name": "device_id",
        "required": true,
        "schema": {
          "examples": [
            "000000ab-00ab-00ab-00ab-0000000000ab"
          ],
          "format": "uuid",
          "type": "string"
        }
      },
      "site_id": {
        "in": "path",
        "name": "site_id",
        "required": true,
        "schema": {
          "examples": [
            "000000ab-00ab-00ab-00ab-0000000000ab"
          ],
          "format": "uuid",
          "type": "string"
        }
      }
    },
    "examples": {
      "HTTP400Example": {
        "value": {
          "detail": "JSON parse error - Expecting value: line 5 column 8 (char 56)"
        }
      },
      "HTTP401Example": {
        "value": {
          "detail": "Authentication credentials were not provided."
        }
      },
      "HTTP403Example": {
        "value": {
          "detail": "You do not have permission to perform this action."
        }
      },
      "HTTP429Example": {
        "value": {
          "detail": "Too Many Request. The API Token used for the request reached the 5000 API Calls per hour threshold"
        }
      }
    },
    "securitySchemes": {
      "apiToken": {
        "description": "Like many other API providers, it’s also possible to generate API Tokens to be used (in HTTP Header) for authentication. An API token ties to a Admin with equal or less privileges.\n\n**Format**:\n  API Token value format is `Token {apitoken}`\n\n**Notes**:\n* an API token generated for a specific admin has the same privilege as the user\n* an API token will be automatically removed if not used for > 90 days\n* SSO admins cannot generate these API tokens. Refer Org level API tokens which can have privileges of a specific Org/Site for more information.",
        "in": "header",
        "name": "Authorization",
        "type": "apiKey",
        "x-scalar-secret-token": "Token YOUR_API_TOKEN"
      },
      "basicAuth": {
        "description": "While our current UI uses Session / Cookie-based authentication, it’s also possible to do Basic Auth.",
        "scheme": "basic",
        "type": "http"
      },
      "csrfToken": {
        "description": "This protects the website against [Cross Site Request Forgery](https://en.wikipedia.org/wiki/Cross-site_request_forgery), all the POST / PUT / DELETE APIs needs to have CSRF token in the AJAX Request header when using Login/Password authentication (with or without MFA)\n\n\nThe CSRF Token is sent back by Mist in the Cookies from the Login Response API Call:\n`cookies[csrftoken]` \n\nThe CSRF Token must be added in the HTTP Request Headers:\n```\nX-CSRFToken: vwvBuq9qkqaKh7lu8tNc0gkvBfEaLAmx\n```",
        "in": "header",
        "name": "X-CSRFToken",
        "type": "apiKey"
      }
    }
  }
}
